### ISSUE TITLE
Sacar recordatorio diario de cuarentena del grupo general del DC

### ISSUE THREAD

**Issue by mnPanic** [comcomUBA/dcubabot#35]
Todos los días a las 00:00 llega un mensaje al grupo de Telegram general de computación que dice:

> Y recuerden amigos, cuarentena no es lo mismo que vacaciones, SEAN RESPONSABLES Y QUÉDENSE EN SUS CASITAS!
> [Foto de He-Man]

Me imagino que la motivación inicial era generar conciencia en la comunidad del DC sobre la seriedad del asunto y que se queden en sus casas. Con la situación actual del país, hay varios que opinamos que el mensaje está quedando viejo, por lo tanto propongo sacarlo.

**Comment by franciscod** [comment]
(ya no está)
