### ISSUE TITLE
Sumar gente al desarrollo

### ISSUE THREAD

**Issue by iglosiggio** [comcomUBA/dcubabot#63]
Durante el 2022 el grueso del laburo agregado al bot vino de parte de @MauricioFIUBA y @franciscod. Entiendo que @rozen03 y @dgarroDC tienen ganas lentamente hacer un pasamanos de la administración del repo (y de la infra atrás).

La gracia de este issue es charlar y tomar una decisión que permita sumar gente al desarrollo del bot. Yo acá ni pincho ni corto (soy codeper nomás) pero creo que ambos dos son personas más que calificadas para sumar al team @comcomUBA/bot.

Obviamente también está del lado de ellos aceptar la invitación 😛.

**Comment by rozen03** [comment]
En primera instancia antes de dar manija a la converzacion, me gustaria tener aclarado si @MauricioFIUBA  y @franciscod  estan de acuerdo con ver esto.

**Comment by MauricioFIUBA** [comment]
Buenas! Yo, por mi parte, no tengo ningún drama en estar en el desarrollo y aportar cuando tenga tiempo

**Comment by franciscod** [comment]
Me prendo!

**Comment by iglosiggio** [comment]
Welcome aboard!
